# Generated by Django 5.0 on 2023-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
