# Generated by Django 5.0 on 2023-12-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_admission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
